"""ASA Patch 33A — Test Suite

Covers:
- WS2: Opportunity evolution history (write_run, compute_evolution, observation_key)
- WS5: Forward Factor live recommendations (FF_RECOMMENDATIONS_ENABLED, FF_EXECUTION_ENABLED)
- WS6: Legacy report summary not generated by default
- WS8: Double-calendar parent structure grouping
- WS9: Roadmap endpoint and AGENTS.md consistency
- Calendar scan_id tagging
"""

from __future__ import annotations

import json
import os
import tempfile
import unittest
from unittest.mock import MagicMock, patch


# ---------------------------------------------------------------------------
# WS2: Opportunity Evolution History
# ---------------------------------------------------------------------------
class TestObservationKey(unittest.TestCase):
    """Deterministic observation_key construction."""

    def setUp(self):
        from app.db.strategy_opportunity_history import _observation_key
        self._key = _observation_key

    def test_calendar_with_front_and_back(self):
        row = {
            "ticker": "AAPL",
            "front_expiration": "2026-07-18",
            "back_expiration": "2026-08-15",
            "direction": "call",
            "strike": "200",
        }
        key = self._key("earnings_calendar", row)
        self.assertIn("AAPL", key)
        self.assertIn("2026-07-18", key)
        self.assertIn("2026-08-15", key)
        self.assertIn("call", key)

    def test_calendar_front_only_is_pre_window(self):
        row = {
            "ticker": "MSFT",
            "front_expiration": "2026-07-25",
            "earnings_date": "2026-07-28",
        }
        key = self._key("earnings_calendar", row)
        self.assertIn("pre_window", key)
        self.assertIn("MSFT", key)
        self.assertIn("2026-07-25", key)

    def test_stock_no_structure(self):
        row = {"ticker": "ELF"}
        key = self._key("forward_factor_calendar", row)
        self.assertEqual(key, "forward_factor_calendar:ELF")

    def test_earnings_calendar_with_date_only(self):
        row = {"ticker": "COST", "earnings_date": "2026-08-01"}
        key = self._key("earnings_calendar", row)
        self.assertIn("earnings_calendar", key)
        self.assertIn("COST", key)
        self.assertIn("2026-08-01", key)

    def test_key_is_lowercase_strategy_uppercase_ticker(self):
        row = {"ticker": "ibm"}
        key = self._key("Stock_Momentum", row)
        # strategy_id lowercased, ticker uppercased
        self.assertTrue(key.startswith("stock_momentum:IBM"))

    def test_same_inputs_produce_same_key(self):
        row = {"ticker": "TSLA", "front_expiration": "2026-07-18", "back_expiration": "2026-08-15"}
        k1 = self._key("earnings_calendar", row)
        k2 = self._key("earnings_calendar", row)
        self.assertEqual(k1, k2)


class TestWriteRun(unittest.TestCase):
    """write_run writes rows and returns accurate counts."""

    def _run(self, db_path, strategy_id, rows, run_id="run-001"):
        from app.db.strategy_opportunity_history import write_run
        return write_run(
            run_id=run_id,
            strategy_results={strategy_id: {"rows": rows}},
            run_date="2026-07-13",
            db_path=db_path,
        )

    def test_first_observation_counted(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            result = self._run(db, "earnings_calendar", [
                {"ticker": "AAPL", "score": 80, "verdict": "PASS"},
            ])
        self.assertEqual(result["rows_written"], 1)
        self.assertEqual(result["first_observations"], 1)
        self.assertEqual(result["verdict_transitions"], 0)
        self.assertEqual(result["stage_transitions"], 0)

    def test_duplicate_run_ignored(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            rows = [{"ticker": "AAPL", "score": 80, "verdict": "PASS"}]
            self._run(db, "earnings_calendar", rows, run_id="run-001")
            result = self._run(db, "earnings_calendar", rows, run_id="run-001")
        # Same run_id → INSERT OR IGNORE → 0 written
        self.assertEqual(result["rows_written"], 0)

    def test_second_run_not_first_observation(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            rows = [{"ticker": "AAPL", "score": 80}]
            self._run(db, "earnings_calendar", rows, run_id="run-001")
            result = self._run(db, "earnings_calendar", rows, run_id="run-002")
        self.assertEqual(result["rows_written"], 1)
        self.assertEqual(result["first_observations"], 0)

    def test_verdict_transition_detected(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            self._run(db, "earnings_calendar",
                      [{"ticker": "AAPL", "score": 60, "verdict": "WATCH"}], "run-001")
            result = self._run(db, "earnings_calendar",
                               [{"ticker": "AAPL", "score": 90, "verdict": "PASS"}], "run-002")
        self.assertEqual(result["verdict_transitions"], 1)

    def test_empty_strategy_results(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            from app.db.strategy_opportunity_history import write_run
            result = write_run("run-x", {}, "2026-07-13", db)
        self.assertEqual(result["rows_written"], 0)
        self.assertEqual(result["rows_attempted"], 0)

    def test_none_row_skipped_gracefully(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            from app.db.strategy_opportunity_history import write_run
            result = write_run("run-x", {"strategy": {"rows": [None, {"ticker": "X"}]}},
                               "2026-07-13", db)
        self.assertEqual(result["rows_written"], 1)

    def test_multiple_strategies_written(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            from app.db.strategy_opportunity_history import write_run
            result = write_run("run-multi", {
                "earnings_calendar": {"rows": [{"ticker": "AAPL"}]},
                "forward_factor_calendar": {"rows": [{"ticker": "ELF"}, {"ticker": "TSLA"}]},
            }, "2026-07-13", db)
        self.assertEqual(result["rows_written"], 3)


class TestComputeEvolution(unittest.TestCase):
    """compute_evolution returns correct delta fields."""

    def _write(self, db, strategy_id, ticker, score, verdict="PASS", run_id="run-001",
               trading_date="2026-07-13"):
        from app.db.strategy_opportunity_history import write_run
        write_run(run_id, {strategy_id: {"rows": [
            {"ticker": ticker, "score": score, "verdict": verdict,
             "trading_date": trading_date}
        ]}}, trading_date, db)

    def test_newly_discovered_when_no_prior(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            from app.db.strategy_opportunity_history import compute_evolution
            result = compute_evolution(
                {"ticker": "NEW", "score": 75, "trading_date": "2026-07-13"},
                "earnings_calendar", db,
            )
        self.assertTrue(result["newly_discovered"])
        self.assertEqual(result["trend_direction"], "new")
        self.assertIn("First observation", result["trend_summary"])

    def test_score_change_1_run_computed(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            self._write(db, "earnings_calendar", "AAPL", 70.0, run_id="run-001",
                        trading_date="2026-07-12")
            from app.db.strategy_opportunity_history import compute_evolution
            result = compute_evolution(
                {"ticker": "AAPL", "score": 80.0, "trading_date": "2026-07-13",
                 "run_id": "run-002", "verdict": "PASS"},
                "earnings_calendar", db,
            )
        self.assertIsNotNone(result["score_change_1_run"])
        self.assertAlmostEqual(result["score_change_1_run"], 10.0, places=1)
        self.assertFalse(result["newly_discovered"])

    def test_verdict_changed_detected(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            self._write(db, "earnings_calendar", "AAPL", 50.0, verdict="WATCH",
                        run_id="run-001", trading_date="2026-07-12")
            from app.db.strategy_opportunity_history import compute_evolution
            result = compute_evolution(
                {"ticker": "AAPL", "score": 90.0, "verdict": "PASS",
                 "trading_date": "2026-07-13", "run_id": "run-002"},
                "earnings_calendar", db,
            )
        self.assertTrue(result["verdict_changed"])
        self.assertEqual(result["verdict_previous"], "WATCH")

    def test_reappeared_after_absence_detected(self):
        """Observation gap > 3 days triggers reappeared_after_absence."""
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            self._write(db, "earnings_calendar", "AAPL", 65.0, run_id="run-001",
                        trading_date="2026-07-01")
            from app.db.strategy_opportunity_history import compute_evolution
            result = compute_evolution(
                {"ticker": "AAPL", "score": 70.0, "trading_date": "2026-07-13",
                 "run_id": "run-002"},
                "earnings_calendar", db,
            )
        self.assertTrue(result["reappeared_after_absence"])

    def test_highest_score_tracked(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            self._write(db, "earnings_calendar", "AAPL", 95.0, run_id="run-001",
                        trading_date="2026-07-10")
            self._write(db, "earnings_calendar", "AAPL", 70.0, run_id="run-002",
                        trading_date="2026-07-11")
            from app.db.strategy_opportunity_history import compute_evolution
            result = compute_evolution(
                {"ticker": "AAPL", "score": 75.0, "trading_date": "2026-07-13"},
                "earnings_calendar", db,
            )
        self.assertAlmostEqual(result["highest_score"], 95.0, places=1)


class TestGetHistory(unittest.TestCase):
    """get_history returns ordered rows for a key."""

    def test_returns_rows_in_reverse_order(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            from app.db.strategy_opportunity_history import write_run, get_history, _observation_key
            row = {"ticker": "TSLA", "score": 60.0}
            write_run("r1", {"stock_momentum": {"rows": [row]}}, "2026-07-11", db)
            write_run("r2", {"stock_momentum": {"rows": [row]}}, "2026-07-12", db)
            write_run("r3", {"stock_momentum": {"rows": [row]}}, "2026-07-13", db)
            key = _observation_key("stock_momentum", row)
            history = get_history(key, "stock_momentum", db_path=db)
        self.assertEqual(len(history), 3)
        # Should be newest first
        self.assertGreaterEqual(history[0]["observed_at"], history[1]["observed_at"])


class TestCleanupOldObservations(unittest.TestCase):
    """cleanup_old_observations removes stale rows."""

    def test_old_rows_removed(self):
        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "hist.db")
            from app.db.strategy_opportunity_history import write_run, cleanup_old_observations
            from app import config
            write_run("r1", {"earnings_calendar": {"rows": [{"ticker": "OLD"}]}},
                      "2020-01-01", db)
            write_run("r2", {"earnings_calendar": {"rows": [{"ticker": "NEW"}]}},
                      "2026-07-13", db)
            deleted = cleanup_old_observations(retention_days=30, db_path=db)
        self.assertGreater(deleted, 0)


# ---------------------------------------------------------------------------
# WS5: Forward Factor Promotion
# ---------------------------------------------------------------------------
class TestFFPromotion(unittest.TestCase):
    """FF_RECOMMENDATIONS_ENABLED=True, FF_EXECUTION_ENABLED=False."""

    def test_ff_recommendations_enabled_default_true(self):
        from app import config
        self.assertTrue(getattr(config, "FF_RECOMMENDATIONS_ENABLED", False))

    def test_ff_execution_enabled_default_false(self):
        from app import config
        self.assertFalse(getattr(config, "FF_EXECUTION_ENABLED", True))

    def test_legacy_forward_factor_dry_run_still_true(self):
        from app import config
        self.assertTrue(config.FORWARD_FACTOR_DRY_RUN)

    def test_pass_row_eligible_when_live(self):
        """When FF_RECOMMENDATIONS_ENABLED=True, PASS rows get can_enter_daily_opportunity."""
        from app import config
        from app.services.forward_factor_service import build_forward_factor_strategy

        class _Hub:
            def get_option_chain(self, *a, **kw):
                return None
            def get_market_data(self, *a, **kw):
                return None

        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "ff.db")
            with patch.object(config, "FF_RECOMMENDATIONS_ENABLED", True), \
                 patch.object(config, "FF_EXECUTION_ENABLED", False), \
                 patch.object(config, "FF_JOURNAL_DB_PATH", db):
                result = build_forward_factor_strategy(
                    ["ELF"],
                    {"ELF": {"current_price": 150, "average_volume_30d": 8_000_000}},
                    _Hub(), run_mode="dev",
                    requirement_plan={"ELF": {"eligible": True, "forward_factor": 0.35,
                                              "meets_ff_min": True, "meets_price_min": True,
                                              "meets_volume_min": True}},
                    run_id="test-live-001", run_date="2026-07-13",
                )
        # dry_run should be False when live mode
        self.assertFalse(result.get("dry_run", True))

    def test_execution_never_triggered(self):
        """FF_EXECUTION_ENABLED=False means no broker calls can happen."""
        from app import config
        self.assertFalse(getattr(config, "FF_EXECUTION_ENABLED", True),
                         "FF_EXECUTION_ENABLED must remain False — no broker writes allowed")

    def test_recommendation_mode_field_on_rows(self):
        """Live-mode rows carry recommendation_mode field."""
        from app import config
        from app.services.forward_factor_service import build_forward_factor_strategy

        class _Hub:
            def get_option_chain(self, *a, **kw):
                return None
            def get_market_data(self, *a, **kw):
                return None

        with tempfile.TemporaryDirectory() as d:
            db = os.path.join(d, "ff.db")
            with patch.object(config, "FF_RECOMMENDATIONS_ENABLED", True), \
                 patch.object(config, "FF_EXECUTION_ENABLED", False), \
                 patch.object(config, "FF_JOURNAL_DB_PATH", db):
                result = build_forward_factor_strategy(
                    ["ELF"],
                    {"ELF": {"current_price": 150, "average_volume_30d": 8_000_000}},
                    _Hub(), run_mode="dev",
                    requirement_plan={"ELF": {"eligible": True, "forward_factor": 0.35,
                                              "meets_ff_min": True}},
                    run_id="test-live-002", run_date="2026-07-13",
                )
        for row in result.get("items", []):
            self.assertIn("recommendation_mode", row)


# ---------------------------------------------------------------------------
# WS6: Legacy Report Summary Deprecation
# ---------------------------------------------------------------------------
class TestLegacySummaryDeprecation(unittest.TestCase):
    """LEGACY_REPORT_SUMMARY_ARCHIVE_ENABLED=False by default."""

    def test_config_default_is_false(self):
        from app import config
        self.assertFalse(getattr(config, "LEGACY_REPORT_SUMMARY_ARCHIVE_ENABLED", True),
                         "LEGACY_REPORT_SUMMARY_ARCHIVE_ENABLED must default to False")

    def test_config_key_exists(self):
        from app import config
        self.assertTrue(hasattr(config, "LEGACY_REPORT_SUMMARY_ARCHIVE_ENABLED"),
                        "LEGACY_REPORT_SUMMARY_ARCHIVE_ENABLED must be defined in config")

    def test_opportunity_history_enabled_default_true(self):
        from app import config
        self.assertTrue(getattr(config, "OPPORTUNITY_HISTORY_ENABLED", False))

    def test_opportunity_history_db_path_configured(self):
        from app import config
        path = getattr(config, "OPPORTUNITY_HISTORY_DB_PATH", None)
        self.assertIsNotNone(path)
        self.assertIn("strategy_opportunity_history", path)


# ---------------------------------------------------------------------------
# WS8: Double Calendar Parent Structure
# ---------------------------------------------------------------------------
class TestBuildDoubleCalendarParents(unittest.TestCase):
    """_build_double_calendar_parents groups call+put calendars on same ticker+expirations."""

    def _make_struct(self, ticker, front, back, option_type, strike="210"):
        return {
            "ticker": ticker,
            "front_expiration": front,
            "back_expiration": back,
            "structure_type": option_type + "_calendar",
            "option_type": option_type,
            "current_debit": 2.50,
            "legs": [{"option_type": option_type, "strike": float(strike)}],
        }

    def test_call_and_put_paired_into_double_calendar(self):
        from app.services.open_options_position_reconciliation_service import _build_double_calendar_parents
        structures = [
            self._make_struct("SBUX", "2026-07-18", "2026-08-15", "call", "82"),
            self._make_struct("SBUX", "2026-07-18", "2026-08-15", "put", "80"),
        ]
        parents, unmatched = _build_double_calendar_parents(structures)
        self.assertEqual(len(parents), 1)
        self.assertEqual(len(unmatched), 0)
        parent = parents[0]
        self.assertEqual(parent["structure_type"], "double_calendar")
        self.assertEqual(parent["ticker"], "SBUX")
        self.assertIn("lower_strike", parent)
        self.assertIn("upper_strike", parent)
        self.assertIn("child_structure_ids", parent)
        self.assertEqual(len(parent["child_structure_ids"]), 2)

    def test_single_leg_stays_unmatched(self):
        from app.services.open_options_position_reconciliation_service import _build_double_calendar_parents
        structures = [
            self._make_struct("AAPL", "2026-07-18", "2026-08-15", "call"),
        ]
        parents, unmatched = _build_double_calendar_parents(structures)
        self.assertEqual(len(parents), 0)
        self.assertEqual(len(unmatched), 1)

    def test_different_tickers_not_paired(self):
        from app.services.open_options_position_reconciliation_service import _build_double_calendar_parents
        structures = [
            self._make_struct("AAPL", "2026-07-18", "2026-08-15", "call"),
            self._make_struct("MSFT", "2026-07-18", "2026-08-15", "put"),
        ]
        parents, unmatched = _build_double_calendar_parents(structures)
        self.assertEqual(len(parents), 0)
        self.assertEqual(len(unmatched), 2)

    def test_different_expirations_not_paired(self):
        from app.services.open_options_position_reconciliation_service import _build_double_calendar_parents
        structures = [
            self._make_struct("SBUX", "2026-07-18", "2026-08-15", "call"),
            self._make_struct("SBUX", "2026-07-25", "2026-08-22", "put"),
        ]
        parents, unmatched = _build_double_calendar_parents(structures)
        self.assertEqual(len(parents), 0)
        self.assertEqual(len(unmatched), 2)

    def test_total_debit_summed_from_children(self):
        from app.services.open_options_position_reconciliation_service import _build_double_calendar_parents
        s1 = self._make_struct("SBUX", "2026-07-18", "2026-08-15", "call")
        s1["current_debit"] = 2.00
        s2 = self._make_struct("SBUX", "2026-07-18", "2026-08-15", "put")
        s2["current_debit"] = 1.75
        parents, _ = _build_double_calendar_parents([s1, s2])
        self.assertAlmostEqual(parents[0]["current_total_debit"], 3.75, places=2)

    def test_four_legs_two_children_one_parent(self):
        """SBUX use-case: 4-leg double calendar → 2 child structures + 1 parent."""
        from app.services.open_options_position_reconciliation_service import _build_double_calendar_parents
        structures = [
            self._make_struct("SBUX", "2026-07-18", "2026-08-15", "call", "82"),
            self._make_struct("SBUX", "2026-07-18", "2026-08-15", "put", "80"),
        ]
        parents, unmatched = _build_double_calendar_parents(structures)
        self.assertEqual(len(parents), 1)
        self.assertEqual(len(unmatched), 0)
        self.assertIn("call_calendar", parents[0])
        self.assertIn("put_calendar", parents[0])
        self.assertIn("lifecycle_action", parents[0])
        self.assertIn("assignment_risk_summary", parents[0])


# ---------------------------------------------------------------------------
# WS1: Calendar Scan ID
# ---------------------------------------------------------------------------
class TestCalendarScanId(unittest.TestCase):
    """Scan ID is generated and stored in the run-scoped calendar scan result."""

    def test_calendar_scan_result_has_scan_id_key_in_source(self):
        """Verify CalendarScanResult includes scan_id and no legacy global state is used."""
        import pathlib
        scan_src = pathlib.Path("app/services/calendar_scan_result_service.py").read_text()
        analysis_src = pathlib.Path("app/services/analysis_service.py").read_text()
        # Check that scan_id is defined in the run-scoped scan-result model.
        self.assertIn("scan_id", scan_src)
        self.assertNotIn("_CALENDAR_SCAN_STATE", analysis_src)

    def test_scan_id_format_in_source(self):
        """Verify scan_id is generated from run_id + uuid hex."""
        import pathlib
        src = pathlib.Path("app/services/analysis_service.py").read_text()
        self.assertIn("scan_id", src)
        # Confirm uuid is used for scan uniqueness
        self.assertIn("uuid4()", src)


# ---------------------------------------------------------------------------
# WS9: Roadmap
# ---------------------------------------------------------------------------
class TestRoadmapJson(unittest.TestCase):
    """config/roadmap.json exists and has correct structure."""

    def _load(self):
        path = os.path.join(os.path.dirname(__file__), "..", "config", "roadmap.json")
        with open(path) as f:
            return json.load(f)

    def test_roadmap_json_exists(self):
        path = os.path.join(os.path.dirname(__file__), "..", "config", "roadmap.json")
        self.assertTrue(os.path.exists(path), "config/roadmap.json must exist")

    def test_roadmap_has_required_fields(self):
        data = self._load()
        for field in ("patch", "schema_version", "patch_title", "active_tickets", "feature_flags"):
            self.assertIn(field, data, f"roadmap.json missing '{field}'")

    def test_roadmap_patch_matches_current_patch(self):
        data = self._load()
        self.assertEqual(data["patch"], "34A.1")

    def test_roadmap_tickets_have_required_fields(self):
        data = self._load()
        for ticket in data["active_tickets"]:
            for f in ("id", "title", "status"):
                self.assertIn(f, ticket, f"ticket {ticket.get('id')} missing '{f}'")

    def test_roadmap_feature_flags_have_required_fields(self):
        data = self._load()
        for flag in data["feature_flags"]:
            for f in ("key", "default"):
                self.assertIn(f, flag, f"feature_flag missing '{f}'")

    def test_no_sensitive_config_exposed(self):
        data = self._load()
        raw = json.dumps(data).lower()
        for sensitive in ("password", "secret", "token", "api_key", "private_key"):
            self.assertNotIn(sensitive, raw,
                             f"roadmap.json must not expose sensitive config: {sensitive}")


class TestAgentsMdConsistency(unittest.TestCase):
    """AGENTS.md patch ID matches config/roadmap.json."""

    def test_agents_md_patch_matches_roadmap(self):
        agents_path = os.path.join(os.path.dirname(__file__), "..", "AGENTS.md")
        roadmap_path = os.path.join(os.path.dirname(__file__), "..", "config", "roadmap.json")
        with open(agents_path) as f:
            agents_content = f.read()
        with open(roadmap_path) as f:
            roadmap = json.load(f)
        roadmap_patch = roadmap.get("patch", "")
        self.assertIn(
            f"patch: {roadmap_patch}",
            agents_content,
            f"AGENTS.md ROADMAP_META patch must match roadmap.json patch={roadmap_patch}",
        )

    def test_agents_md_has_roadmap_meta_block(self):
        agents_path = os.path.join(os.path.dirname(__file__), "..", "AGENTS.md")
        with open(agents_path) as f:
            content = f.read()
        self.assertIn("ROADMAP_META", content)
        self.assertIn("roadmap_json:", content)


class TestDevRoadmapEndpoint(unittest.TestCase):
    """GET /api/dev/roadmap returns roadmap JSON."""

    def _client(self):
        import sys
        sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
        from app.main import app as flask_app
        flask_app.config["TESTING"] = True
        return flask_app.test_client()

    def test_roadmap_endpoint_registered_in_source(self):
        """Verify /api/dev/roadmap is registered in app/main.py source."""
        import pathlib
        src = pathlib.Path("app/main.py").read_text()
        self.assertIn("/api/dev/roadmap", src,
                      "/api/dev/roadmap route must be registered in app/main.py")

    def test_roadmap_endpoint_exists(self):
        from app import config
        client = self._client()
        sentinel = "test-dev-roadmap-token"
        with patch.object(config, "ENABLE_DEV_DIAGNOSTICS_ENDPOINTS", True), \
             patch.object(config, "DEV_API_TOKEN", sentinel):
            resp = client.get(f"/api/dev/roadmap?token={sentinel}")
        # Either 200 (authorized) or 403 (token mismatch) — never 404 if route exists
        self.assertNotEqual(resp.status_code, 404,
                            "/api/dev/roadmap endpoint must be registered")

    def test_roadmap_response_has_patch_when_authorized(self):
        from app import config
        client = self._client()
        sentinel = "test-dev-token-roadmap"
        with patch.object(config, "ENABLE_DEV_DIAGNOSTICS_ENDPOINTS", True), \
             patch.object(config, "DEV_API_TOKEN", sentinel):
            resp = client.get(f"/api/dev/roadmap?token={sentinel}")
        if resp.status_code == 200:
            data = resp.get_json()
            self.assertIn("current_patch", data)
            self.assertEqual(data["current_patch"], "34A.1")


if __name__ == "__main__":
    unittest.main()
